### ISSUE TITLE
question about the classification acc

### ISSUE THREAD

**Issue by wxz1996** [eric8607242/OSNASLib#1]
Thank you for this work, I have benefited a lot , but when i try this code with your config, the test results seem to be a bit problem; For the classification task with the CIFAR100, when i test the  "Proxyless net" with "differentiable_differentiable.yml",  best val performence is 0.6129, "SPOS net" with "uniform_evolution.yml", best val performance only 0.373 with 200 epochs; i have no idea about that, have you save the test result?

**Comment by eric8607242** [comment]
Hello, thanks for your question. : )

Does the val performance is evaluated on supernet?

For different training strategies, the val performance of the supernet will be very different.
For example, the supernet val performance trained by differentiable strategy is often higher than the supernet trained by the uniform strategy. 
The reason I think is that the differentiable strategy weight the output of each candidate block by architecture parameters in each layer of supernet, which has an effect similar to the ensemble for training supernet and makes supernet more stable to train.
On the other hand, uniform strategy uniformly samples different candidate blocks in each layer for each iteration, which makes the supernet is more difficult to train the supernet. Besides, each candidate block can only be updated 1/N times (N is the number of candidate blocks) in one epoch.

However, the val performance of the supernet is not very important because the supernet is only used to "rank" the network in the search space to get the best architecture instead of the absolute value of val performance.
Therefore, to compare different training strategies or searching strategies fairly, we usually train the search network from scratch to evaluate the performance of the search network. (By the way, there are some works that can directly evaluate the network sampled from the supernet without training from scratch.) 
You can get the search network in `./logs/[EXPERIMENT TITLE]/searched_model_architecture.npy`.

In OSNASLIB, you can check the config file './config/classification/evaluate_classification.yml' to check the config for training from scratch. (Sorry I will update the readme for how to train from scratch the search network.)
The command line for training from scratch is as:
`python3 main.py -c ./config/classification/evaluate_classification.yml --title [EXPERIMENT TITLE]`

I holp these are useful for you!
If you have any questions, please feel free to launch a new issue.
